apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: datastoreapp
  namespace: datastorepoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datastoreapp
  template:
    metadata:
      labels:
        app: datastoreapp
    spec:
      containers:
      - name: bigimage
        image: mdshoaib707/datastore:working
        command: ["/bin/sh"]
        args: ["-c", "mvn -Plocal clean jetty:run-exploded -DprojectID=kohls-mobile-sandbox -f /getting-started-java/bookshelf/2-structured-data/pom.xml"]
        ports:
        - name: datastoreport
          containerPort: 8080
