apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: tmpname
  namespace: tmpnamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tmpmatchlabels
  template:
    metadata:
      labels:
        app: tmpname
    spec:
      containers:
      - name: tmpcontainername
        image: tmpimage
        command: ["/bin/sh"]
        args: ["-c", "mvn -Plocal clean jetty:run-exploded -DprojectID=kohls-mobile-sandbox -f /getting-started-java/bookshelf/2-structured-data/pom.xml"]
        ports:
        - name: tmpportname
          containerPort: tmpportnumber
